// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MatchMetadataInput } from "./MatchMetadataInput";

export type CherryMatchTaskInput = { region: string, locale: string, myPuuid: string, metadata: MatchMetadataInput, info: Record<string, unknown>, };
