// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CherryMatchParticipantInput } from "./CherryMatchParticipantInput";

export type CherryMatchInfoInput = { gameEndTimestamp: bigint, gameDuration: number, queueId: number, participants: Array<CherryMatchParticipantInput>, };
