// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CherryMatchInfoInput } from "./CherryMatchInfoInput";
import type { MatchMetadataInput } from "./MatchMetadataInput";

export type CherryMatchTaskInput = { metadata: MatchMetadataInput, info: CherryMatchInfoInput, queueName: string, puuid: string, region: string, locale: string, };
