// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MasteryData } from "./MasteryData";
import type { RankData } from "./RankData";

export type ClashPlayer = { puuid: string, position: string, role: string, highestRank: RankData | null, masteries: Array<MasteryData>, level: number, gameName: string, tagLine: string, profileIconId: number, };
