// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DefaultParametersInput = { puuid: string, region: string, level: number, gameName: string, tagLine: string, profileIconId: number, locale: string, };
