// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FileResult =
    | { type: 'temp'; data: string }
    | { type: 'persistent'; name: string; data: string | null }
    | { type: 'local'; path: string };
