// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GraphLpEntryInput } from "./GraphLpEntryInput";

export type GraphTaskInput = { queue: string, history: Array<GraphLpEntryInput>, puuid: string, region: string, locale: string, level: number, gameName: string, tagLine: string, profileIconId: number, };
