// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GraphLpEntryInput = { lp: number, rank: string, tier: string, time: string | null, };
