// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MatchParticipantInput } from "./MatchParticipantInput";
import type { MatchTeamInput } from "./MatchTeamInput";

export type MatchInfoInput = { gameEndTimestamp: bigint, gameDuration: number, queueId: number, participants: Array<MatchParticipantInput>, teams: Array<MatchTeamInput>, };
