// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MatchPerkStyleInput } from "./MatchPerkStyleInput";
import type { MatchStatPerksInput } from "./MatchStatPerksInput";

export type MatchPerksInput = { styles: Array<MatchPerkStyleInput>, statPerks?: MatchStatPerksInput, };
