// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MatchInfoInput } from "./MatchInfoInput";
import type { MatchMetadataInput } from "./MatchMetadataInput";

export type MatchTaskInput = { metadata: MatchMetadataInput, info: MatchInfoInput, lpGain: number | null, queueName: string, puuid: string, region: string, locale: string, };
