// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MatchInfoInput } from "./MatchInfoInput";
import type { MatchMetadataInput } from "./MatchMetadataInput";
import type { TierChangeInput } from "./TierChangeInput";

export type MatchTaskInput = { metadata: MatchMetadataInput, info: MatchInfoInput, lpGain: number | null, tierChange?: TierChangeInput, teams?: { [key in string]: number }, queueName: string, puuid: string, region: string, locale: string, };
