// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MatchBanInput } from "./MatchBanInput";

export type MatchTeamInput = { bans: Array<MatchBanInput>, teamId: number, win: boolean, };
