// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MatchPerksInput } from "./MatchPerksInput";

export type MatchParticipantInput = { assists: number, champLevel: number, championName: string, deaths: number, gameEndedInEarlySurrender: boolean, goldEarned: number, kills: number, item0: number, item1: number, item2: number, item3: number, item4: number, item5: number, item6: number, puuid: string, riotIdGameName: string, riotIdTagline: string, roleBoundItem: number | null, summoner1Id: number, summoner2Id: number, teamId: number, totalDamageDealtToChampions: number, totalMinionsKilled: number, visionScore: number, win: boolean, perks: MatchPerksInput, };
