// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Rank } from "./Rank";
import type { Tier } from "./Tier";

export type RankData = { queueType: string, wins: number, losses: number, tierIndex: number, tier: Tier, rankIndex: number, rank: Rank, lp: number, };
