// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RankQueueEntryInput } from "./RankQueueEntryInput";

export type RankTaskInput = { ranks: Array<RankQueueEntryInput>, puuid: string, region: string, locale: string, level: number, gameName: string, tagLine: string, profileIconId: number, };
