// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StreakInput } from "./StreakInput";

export type RankQueueEntryInput = { queueType: string, wins: number, losses: number, tier: string, rank: string, leaguePoints: number, streak?: StreakInput, };
