// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MatchMetadataInput } from "./MatchMetadataInput";
import type { MatchParticipantInput } from "./MatchParticipantInput";
import type { PlayerTagInput } from "./PlayerTagInput";
import type { TimelineItemEventInput } from "./TimelineItemEventInput";
import type { TimelineWardEventInput } from "./TimelineWardEventInput";

export type ReportTaskInput = { metadata: MatchMetadataInput, queueName: string, gameCreation: bigint, gameDuration: number, participant: MatchParticipantInput, teamTotalDamage: number, teamTotalKills: number, timelineItems: Array<TimelineItemEventInput>, timelineWards: Array<TimelineWardEventInput>, tags: Array<PlayerTagInput>, puuid: string, region: string, locale: string, level: number, gameName: string, tagLine: string, profileIconId: number, };
