// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MatchMetadataInput } from "./MatchMetadataInput";
import type { MatchParticipantInput } from "./MatchParticipantInput";

export type ReportTaskInput = { metadata: MatchMetadataInput, queueName: string, gameCreation: bigint, gameDuration: number, participant: MatchParticipantInput, teamTotalDamage: number, teamTotalKills: number, puuid: string, region: string, locale: string, level: number, gameName: string, tagLine: string, profileIconId: number, };
