// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpectatorParticipantInput } from './SpectatorParticipantInput';

export type SpectatorTaskInput = {
    queueId: number;
    gameLength: number;
    mapId: number;
    participants: Array<SpectatorParticipantInput>;
    puuid: string;
    region: string;
    level: number;
    gameName: string;
    tagLine: string;
    profileIconId: number;
    locale: string;
};
