// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpectatorPerksInput } from "./SpectatorPerksInput";

export type SpectatorParticipantInput = { teamId: number, championId: number, riotId: string, puuid: string, spell1Id: number, spell2Id: number, perks: SpectatorPerksInput, };
