// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpectatorBannedChampionInput } from "./SpectatorBannedChampionInput";
import type { SpectatorParticipantInput } from "./SpectatorParticipantInput";

export type SpectatorTaskInput = { queueName: string, gameLength: number, mapName: string, participants: Array<SpectatorParticipantInput>, bannedChampions: Array<SpectatorBannedChampionInput>, puuid: string, region: string, locale: string, };
