// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BannerType } from "./BannerType";
import type { RankTier } from "./RankTier";
import type { SummonerChallengeInput } from "./SummonerChallengeInput";

export type SummonerTaskInput = { titleId: string | null, crest: number, prestigeCrest: number, banner: BannerType, highestRank: RankTier | null, challenges: Array<bigint>, userChallenges: Array<SummonerChallengeInput>, puuid: string, region: string, level: number, gameName: string, tagLine: string, profileIconId: number, locale: string, };
