// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClashPlayer } from "./ClashPlayer";

export type TeamTaskInput = { abbreviation: string, name: string, iconId: number, tier: number, captain: string, players: Array<ClashPlayer>, puuid: string, region: string, locale: string, };
