// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RankQueueEntryInput } from "./RankQueueEntryInput";
import type { TeamMasteryInput } from "./TeamMasteryInput";

export type TeamPlayerInput = { puuid: string, position: string, role: string, profileIconId: number, level: number, highestRank: RankQueueEntryInput | null, gameName: string, tagLine: string, masteries: Array<TeamMasteryInput>, };
