// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Rank } from "./Rank";
import type { Tier } from "./Tier";

export type TierChangeInput = { isPromotion: boolean, tier: Tier, rank?: Rank, };
