/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
    T extends ColumnType<infer S, infer I, infer U>
        ? ColumnType<S, I | undefined, U>
        : ColumnType<T, T | undefined, T>;

export interface Account {
    account_id: string;
    discord_id: string;
    gameName: string;
    id: Generated<number>;
    puuid: string;
    region: string;
    summoner_id: string;
    tagLine: string;
}

export interface Lp {
    account_id: number;
    id: Generated<number>;
    LP: number;
    queue: string;
    rank: string;
    tier: string;
    time: Generated<Date>;
}

export interface MatchLp {
    accountId: number;
    gain: Generated<number | null>;
    id: Generated<number>;
    lp: number;
    matchId: string;
}

export interface DB {
    account: Account;
    lp: Lp;
    match_lp: MatchLp;
}
