/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
    T extends ColumnType<infer S, infer I, infer U>
        ? ColumnType<S, I | undefined, U>
        : ColumnType<T, T | undefined, T>;

export interface Account {
    discord_id: Generated<string | null>;
    gameName: string;
    id: Generated<number>;
    puuid: string;
    region: string;
    tagLine: string;
}

export interface Emoji {
    emoji_id: string;
    guild: string;
    id: Generated<number>;
    name: string;
}

export interface InMemory {
    key: string;
    value: string;
}

export interface Lp {
    account_id: number;
    id: Generated<number>;
    LP: number;
    queue: string;
    rank: string;
    tier: string;
    time: Generated<Date | null>;
}

export interface MatchLp {
    accountId: number;
    gain: Generated<number | null>;
    id: Generated<number>;
    lp: number;
    matchId: string;
}

export interface DuoMatch {
    created_at: Generated<Date | null>;
    id: Generated<number>;
    match_id: string;
    puuid1: string;
    puuid2: string;
}

export interface MatchParticipantStat {
    account_id: number | null;
    assists: number;
    champion_id: number;
    created_at: Generated<Date | null>;
    damage_dealt: number;
    damage_taken: number;
    deaths: number;
    gold_earned: number;
    id: Generated<number>;
    kills: number;
    match_id: string;
    minions_killed: number;
    puuid: string;
    queue_id: number;
    vision_score: number;
    wards_killed: number;
    wards_placed: number;
    win: boolean;
}

export interface UserSettings {
    command_presets: Generated<string | null>;
    discord_id: string;
    language: Generated<string | null>;
}

export interface DB {
    account: Account;
    duo_match: DuoMatch;
    emoji: Emoji;
    in_memory: InMemory;
    lp: Lp;
    match_lp: MatchLp;
    match_participant_stat: MatchParticipantStat;
    user_settings: UserSettings;
}
