[package]
name = "worker"
version = "0.1.0"
edition = "2024"

[features]
default = []
export-ts = []
save = []

[dependencies]
ab_glyph = "0.2.32"
futures-util = "0.3.32"
image = "0.25.10"
imageproc = "0.26.2"
insta = "1.47.2"
insta-image = { version = "1.0.0", features = ["png"] }
rayon = "1.12.0"
reqwest = { version = "0.13.3", features = ["json"] }
rusttype = "0.9.3"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tokio = { version = "1.52.3", features = ["full"] }
tokio-tungstenite = "0.29.0"
ts-rs = "12.0.1"
url = "2.5.8"
tracing = { version = "0.1.41", features = ["attributes"] }
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "fmt"] }
